# Generated by Django 4.2.7 on 2023-11-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMemberModel',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='FamilyModel',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
            ],
            options={
                'managed': False,
            },
            bases=('vaxTracker_app.usermodel',),
        ),
        migrations.CreateModel(
            name='HouseHeadModel',
            fields=[
            ],
            options={
                'managed': False,
            },
            bases=('vaxTracker_app.usermodel',),
        ),
        migrations.CreateModel(
            name='AdminModel',
            fields=[
            ],
            bases=('vaxTracker_app.usermodel',),
        ),
    ]
