# Generated by Django 4.2.7 on 2023-12-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxTracker_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HouseHeadModel',
        ),
    ]
